# Generated by Django 6.0.4 on 2026-06-02 12:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("jackietrade", "0002_watchlistitem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sector",
            name="description",
        ),
    ]
