# Generated by Django 6.0.4 on 2026-06-11 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jackietrade', '0006_asset_notes_alter_asset_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jackietrade.sector', verbose_name='Secteur'),
        ),
    ]
