# Generated by Django 6.0.4 on 2026-06-22 14:13

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jackietrade', '0011_alter_asset_sector_alter_watchlistitem_asset'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeJournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session_date', models.DateField()),
                ('title', models.CharField(max_length=200)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('observation_notes', models.TextField(blank=True)),
                ('market_context', models.TextField(blank=True)),
                ('entry_price', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('stop_loss', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('take_profit', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('confidence_level', models.IntegerField(blank=True, choices=[(1, 'Très faible'), (2, 'Faible'), (3, 'Moyenne'), (4, 'Haute'), (5, 'Très haute')], null=True)),
                ('execution_notes', models.TextField(blank=True)),
                ('entry_order_at', models.DateTimeField(blank=True, null=True)),
                ('entry_quantity', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2000)])),
                ('entry_price_executed', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('result_notes', models.TextField(blank=True)),
                ('exit_order_at', models.DateTimeField(blank=True, null=True)),
                ('exit_quantity', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2000)])),
                ('exit_price', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('exit_reason', models.CharField(blank=True, choices=[('stop_loss', 'Stop Loss'), ('take_profit', 'Take Profit'), ('open', 'Position ouverte')], default='open', max_length=20)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jackietrade.asset')),
            ],
        ),
        migrations.CreateModel(
            name='TradeJournalScreenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='trade_journal/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('journal_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='jackietrade.tradejournalentry')),
            ],
        ),
        migrations.CreateModel(
            name='TradingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trading_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
