# Generated by Django 6.0.4 on 2026-06-26 15:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jackietrade", "0014_alter_watchlistitem_asset_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="isin",
            field=models.CharField(
                blank=True,
                max_length=12,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="L'ISIN doit être composé de 2 lettres,"
                        + "9 caractères alphanumériques et 1 chiffre.",
                        regex="^[A-Z]{2}[A-Z0-9]{9}[0-9]$",
                    )
                ],
            ),
        ),
    ]
