# Generated by Django 6.0.4 on 2026-06-28 09:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jackietrade", "0016_tradejournalentry_status_tradingsettings_strategy"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tradejournalentry",
            name="title",
        ),
        migrations.AddField(
            model_name="tradejournalentry",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="journals",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
