# Generated by Django 6.0.4 on 2026-06-28 18:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("jackietrade", "0017_remove_tradejournalentry_title_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tradejournalentry",
            old_name="entry_price",
            new_name="planned_entry_price",
        ),
        migrations.RenameField(
            model_name="tradejournalentry",
            old_name="stop_loss",
            new_name="planned_stop_loss",
        ),
        migrations.RenameField(
            model_name="tradejournalentry",
            old_name="take_profit",
            new_name="planned_take_profit",
        ),
    ]
