# Generated by Django 6.0.4 on 2026-08-06 19:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "jackietrade",
            "0018_rename_entry_price_tradejournalentry_planned_entry_price_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="tradejournalentry",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Préparation"),
                    ("watching", "Sous surveillance"),
                    ("open", "Position ouverte"),
                    ("closed", "Position clôturée"),
                    ("cancelled", "Scénario abandonné"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
    ]
