# Generated by Django 6.0.3 on 2026-04-13 15:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='users/%Y/%m/%d')),
                ('date_of_birth', models.IntegerField(blank=True, null=True)),
                ('theme', models.CharField(default='light', max_length=20)),
                ('language', models.CharField(default='fr', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'users profil',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=50, unique=True, verbose_name='email address')),
                ('trigram', models.CharField(max_length=5)),
                ('usertype', models.CharField(blank=True, choices=[('member', 'Member'), ('supermember', 'Supermember')], default='member', max_length=30)),
                ('last_password_change', models.DateTimeField(blank=True, null=True, verbose_name='Dernier changement de mot de passe')),
                ('last_email_change', models.DateTimeField(blank=True, null=True, verbose_name="Dernier changement d'email")),
                ('last_trigram_change', models.DateTimeField(blank=True, null=True, verbose_name='Dernier changement de trigram')),
                ('stopwatch', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text="Les groupes auxquels appartient l'utilisateur", related_name='myuser_set', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text="Les permissions de l'utilisateur", related_name='myuser_permission_set', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'ordering': ['-trigram'],
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('account.myuser',),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.AddIndex(
            model_name='myuser',
            index=models.Index(fields=['-trigram'], name='account_myu_trigram_793456_idx'),
        ),
    ]
