# Generated by Django 6.0.4 on 2026-09-14 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DevappsApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Application",
                "verbose_name_plural": "Applications",
            },
        ),
        migrations.CreateModel(
            name="DevappsVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                ("objectif", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Version",
                "verbose_name_plural": "Versions",
            },
        ),
        migrations.CreateModel(
            name="DevappsAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("bug", "Bug"),
                            ("improvement", "Amélioration"),
                            ("formation", "Formation"),
                            ("create", "Création"),
                            ("analysis", "Analyse"),
                            ("test", "Test"),
                            ("refactoring", "Refactoring"),
                            ("documentation", "Documentation"),
                            ("deployment", "Déploiement"),
                        ],
                        default="analysis",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                ("details", models.TextField(blank=True)),
                ("priority", models.PositiveIntegerField(default=100)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("todo", "À faire"),
                            ("cancel", "Annulé"),
                            ("in_progress", "En cours"),
                            ("done", "Terminé"),
                        ],
                        default="todo",
                        max_length=20,
                    ),
                ),
                (
                    "estimated_time",
                    models.PositiveIntegerField(help_text="Temps estimé en minutes"),
                ),
                (
                    "achieved_time",
                    models.PositiveIntegerField(
                        blank=True, help_text="Temps réalisé en minutes", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("planned", models.BooleanField(default=False)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="actions",
                        to="devapps.devappsapplication",
                    ),
                ),
                (
                    "version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="actions",
                        to="devapps.devappsversion",
                    ),
                ),
            ],
        ),
    ]
