# Generated by Django 6.0.4 on 2026-08-06 19:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DictavoixTheme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Thème Dictavoix",
                "verbose_name_plural": "Thèmes Dictavoix",
            },
        ),
        migrations.CreateModel(
            name="DictavoixExercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("text", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dictavoix_exercises",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "theme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="exercises",
                        to="dictavoix.dictavoixtheme",
                    ),
                ),
            ],
            options={
                "verbose_name": "Exercice Dictavoix",
                "verbose_name_plural": "Exercices Dictavoix",
            },
        ),
        migrations.CreateModel(
            name="DictavoixSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("error_count", models.PositiveIntegerField(default=0)),
                ("total_word_count", models.PositiveIntegerField(default=0)),
                ("dictionary_word_count", models.PositiveIntegerField(default=0)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="dictavoix.dictavoixexercise",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dictavoix_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Session Dictavoix",
                "verbose_name_plural": "Sessions Dictavoix",
            },
        ),
        migrations.CreateModel(
            name="DictavoixDictionaryWord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("word", models.CharField(max_length=120)),
                (
                    "pronunciation_hint",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "theme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dictionary_words",
                        to="dictavoix.dictavoixtheme",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mot dictionnaire",
                "verbose_name_plural": "Mots dictionnaire",
                "unique_together": {("theme", "word")},
            },
        ),
    ]
