# Generated by Django 6.0.4 on 2026-05-14 21:02

import datetime

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ColorParameter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("6-verylow", "Très faible"),
                            ("5-low", "Faible"),
                            ("4-normal", "Normale"),
                            ("3-medium", "Moyenne"),
                            ("2-high", "Élevée"),
                            ("1-highest", "Très élevée"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "periodic",
                    models.CharField(
                        choices=[
                            ("*-Every", "tous les cas"),
                            ("01-none", "une seule fois"),
                            ("02-everyday", "Tous les jours"),
                            ("03-every2days", "Tous les 2 jours"),
                            ("04-every3days", "Tous les 3 jours"),
                            ("05-every4days", "Tous les 4 jours"),
                            ("06-every5days", "Tous les 5 jours"),
                            ("07-everyweek", "Toutes les semaines"),
                            ("08-every10days", "Tous les 10 jours"),
                            ("09-every2weeks", "Toutes les 2 semaines"),
                            ("10-every3weeks", "Toutes les 3 semaines"),
                            ("11-everymonth", "Tous les mois"),
                            ("12-every6weeks", "Toutes les 6 semaines"),
                            ("13-every2months", "Tous les 2 mois"),
                            ("14-every3months", "Tous les 3 mois"),
                            ("15-every4months", "Tous les 4 mois"),
                            ("16-every6months", "Tous les 6 mois"),
                            ("17-everyyear", "Tous les ans"),
                            ("18-every18months", "Tous les 18 mois"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("*-Every", "tous les cas"),
                            ("01-organisation", "Organisation"),
                            ("02-compta", "Compta"),
                            ("03-achat", "Achats"),
                            ("04-sport", "Sport"),
                            ("05-sante", "Santé"),
                            ("06-contact", "Contact"),
                            ("07-informatique", "Informatique"),
                            ("08-menage", "Menage"),
                            ("09-jardin", "Jardin"),
                            ("10-doudou", "Doudou"),
                            ("11-bricoles", "Bricoles"),
                            ("12-couture", "Couture"),
                            ("13-loisirs", "Loisirs"),
                            ("14-vacances", "Vacances"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "place",
                    models.CharField(
                        choices=[
                            ("*-Every", "tous les cas"),
                            ("cantin", "Cantin"),
                            ("chm", "CHM"),
                            ("genese", "Genèse"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Entrez une couleur au " +
                                "format hexadécimal valide (ex: #1A2B3C).",
                                regex="^#[0-9A-Fa-f]{6}$",
                            )
                        ],
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("priority", "periodic", "category", "place"),
                        name="unique_color_combination",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Memo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("todo", "À faire"),
                            ("in_progress", "En cours"),
                            ("done", "Terminé"),
                            ("report", "Reporté"),
                            ("cancel", "Annulé"),
                        ],
                        default="memo",
                        max_length=20,
                    ),
                ),
                (
                    "duration",
                    models.IntegerField(
                        default=30,
                        validators=[
                            django.core.validators.MinValueValidator(10),
                            django.core.validators.MaxValueValidator(800),
                        ],
                    ),
                ),
                ("description", models.TextField()),
                (
                    "appointment",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("rdv", "Rendez-vous"),
                            ("birthday", "Anniversaire"),
                            ("festival", "Fête"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("01-organisation", "Organisation"),
                            ("02-compta", "Compta"),
                            ("03-achat", "Achats"),
                            ("04-sport", "Sport"),
                            ("05-sante", "Santé"),
                            ("06-contact", "Contact"),
                            ("07-informatique", "Informatique"),
                            ("08-menage", "Menage"),
                            ("09-jardin", "Jardin"),
                            ("10-doudou", "Doudou"),
                            ("11-bricoles", "Bricoles"),
                            ("12-couture", "Couture"),
                            ("13-loisirs", "Loisirs"),
                            ("14-vacances", "Vacances"),
                        ],
                        default="01-organisation",
                        max_length=20,
                    ),
                ),
                (
                    "place",
                    models.CharField(
                        choices=[
                            ("cantin", "Cantin"),
                            ("chm", "CHM"),
                            ("genese", "Genèse"),
                        ],
                        default="partout",
                        max_length=20,
                    ),
                ),
                (
                    "periodic",
                    models.CharField(
                        choices=[
                            ("01-none", "une seule fois"),
                            ("02-everyday", "Tous les jours"),
                            ("03-every2days", "Tous les 2 jours"),
                            ("04-every3days", "Tous les 3 jours"),
                            ("05-every4days", "Tous les 4 jours"),
                            ("06-every5days", "Tous les 5 jours"),
                            ("07-everyweek", "Toutes les semaines"),
                            ("08-every10days", "Tous les 10 jours"),
                            ("09-every2weeks", "Toutes les 2 semaines"),
                            ("10-every3weeks", "Toutes les 3 semaines"),
                            ("11-everymonth", "Tous les mois"),
                            ("12-every6weeks", "Toutes les 6 semaines"),
                            ("13-every2months", "Tous les 2 mois"),
                            ("14-every3months", "Tous les 3 mois"),
                            ("15-every4months", "Tous les 4 mois"),
                            ("16-every6months", "Tous les 6 mois"),
                            ("17-everyyear", "Tous les ans"),
                            ("18-every18months", "Tous les 18 mois"),
                        ],
                        default="partout",
                        max_length=20,
                    ),
                ),
                ("report_date", models.DateField(blank=True, null=True)),
                ("planned_date", models.DateField(default=datetime.date(2026, 5, 15))),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("6-verylow", "Très faible"),
                            ("5-low", "Faible"),
                            ("4-normal", "Normale"),
                            ("3-medium", "Moyenne"),
                            ("2-high", "Élevée"),
                            ("1-highest", "Très élevée"),
                        ],
                        default="4-normal",
                        max_length=20,
                    ),
                ),
                ("done_date", models.DateField(blank=True, null=True)),
                ("note", models.TextField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_memos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "who",
                    models.ManyToManyField(
                        blank=True,
                        related_name="assigned_memos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MemoHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("created", "Création"),
                            ("updated", "Mise à jour"),
                            ("deleted", "Suppression"),
                            ("restored", "Restauration"),
                        ],
                        max_length=20,
                    ),
                ),
                ("changes", models.JSONField(blank=True, default=dict)),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="memo_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "memo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="journaling.memo",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
    ]
