# Generated by Django 6.0.4 on 2026-05-31 05:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journaling', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colorparameter',
            name='periodic',
            field=models.CharField(choices=[('*-Every', 'tous les cas'), ('01-none', 'une seule fois'), ('02-everyday', 'Tous les jours'), ('03-every2days', 'Tous les 2 jours'), ('04-every3days', 'Tous les 3 jours'), ('05-every4days', 'Tous les 4 jours'), ('06-every5days', 'Tous les 5 jours'), ('07-everyweek', 'Toutes les semaines'), ('08-every10days', 'Tous les 10 jours'), ('09-every2weeks', 'Toutes les 2 semaines'), ('10-every3weeks', 'Toutes les 3 semaines'), ('11-everymonth', 'Tous les mois'), ('12-every6weeks', 'Toutes les 6 semaines'), ('13-every2months', 'Tous les 2 mois'), ('14-every3months', 'Tous les 3 mois'), ('15-every4months', 'Tous les 4 mois'), ('16-every6months', 'Tous les 6 mois'), ('17-everyyear', 'Tous les ans'), ('18-every18months', 'Tous les 18 mois'), ('19-every2years', 'Tous les 2 ans')], max_length=20),
        ),
        migrations.AlterField(
            model_name='colorparameter',
            name='place',
            field=models.CharField(choices=[('*-Every', 'tous les cas'), ('cantin-ext', 'Cantin exterieur'), ('cantin-int', 'Cantin interieur'), ('chm', 'CHM'), ('genese', 'Genèse'), ('fontaine', 'Fontaine')], max_length=20),
        ),
        migrations.AlterField(
            model_name='colorparameter',
            name='priority',
            field=models.CharField(choices=[('6-lowest', 'Très faible'), ('5-low', 'Faible'), ('4-normal', 'Normale'), ('3-medium', 'Moyenne'), ('2-high', 'Élevée'), ('1-highest', 'Très élevée')], max_length=20),
        ),
        migrations.AlterField(
            model_name='memo',
            name='periodic',
            field=models.CharField(choices=[('01-none', 'une seule fois'), ('02-everyday', 'Tous les jours'), ('03-every2days', 'Tous les 2 jours'), ('04-every3days', 'Tous les 3 jours'), ('05-every4days', 'Tous les 4 jours'), ('06-every5days', 'Tous les 5 jours'), ('07-everyweek', 'Toutes les semaines'), ('08-every10days', 'Tous les 10 jours'), ('09-every2weeks', 'Toutes les 2 semaines'), ('10-every3weeks', 'Toutes les 3 semaines'), ('11-everymonth', 'Tous les mois'), ('12-every6weeks', 'Toutes les 6 semaines'), ('13-every2months', 'Tous les 2 mois'), ('14-every3months', 'Tous les 3 mois'), ('15-every4months', 'Tous les 4 mois'), ('16-every6months', 'Tous les 6 mois'), ('17-everyyear', 'Tous les ans'), ('18-every18months', 'Tous les 18 mois'), ('19-every2years', 'Tous les 2 ans')], default='partout', max_length=20),
        ),
        migrations.AlterField(
            model_name='memo',
            name='place',
            field=models.CharField(choices=[('cantin-ext', 'Cantin exterieur'), ('cantin-int', 'Cantin interieur'), ('chm', 'CHM'), ('genese', 'Genèse'), ('fontaine', 'Fontaine')], default='partout', max_length=20),
        ),
        migrations.AlterField(
            model_name='memo',
            name='planned_date',
            field=models.DateField(default=datetime.date(2026, 6, 1)),
        ),
        migrations.AlterField(
            model_name='memo',
            name='priority',
            field=models.CharField(choices=[('6-lowest', 'Très faible'), ('5-low', 'Faible'), ('4-normal', 'Normale'), ('3-medium', 'Moyenne'), ('2-high', 'Élevée'), ('1-highest', 'Très élevée')], default='4-normal', max_length=20),
        ),
    ]
