# Generated by Django 6.0.4 on 2026-06-01 10:54

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journaling", "0002_alter_colorparameter_periodic_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="memo",
            name="planned_date",
            field=models.DateField(default=datetime.date(2026, 6, 2)),
        ),
    ]
