# Generated by Django 6.0.4 on 2026-06-26 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jackietrade", "0012_tradejournalentry_tradejournalscreenshot_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="watchlistitem",
            name="watchlist",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="watchlist",
                to="jackietrade.watchlist",
            ),
        ),
    ]
