# Generated by Django 6.0.4 on 2026-06-26 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jackietrade", "0013_alter_watchlistitem_watchlist"),
    ]

    operations = [
        migrations.AlterField(
            model_name="watchlistitem",
            name="asset",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="watchlist_items",
                to="jackietrade.asset",
            ),
        ),
        migrations.AlterField(
            model_name="watchlistitem",
            name="watchlist",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="jackietrade.watchlist",
            ),
        ),
    ]
