# Generated by Django 6.0.4 on 2026-06-27 10:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jackietrade", "0015_asset_isin"),
    ]

    operations = [
        migrations.AddField(
            model_name="tradejournalentry",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Préparation"),
                    ("open", "Position ouverte"),
                    ("closed", "Position clôturée"),
                    ("cancelled", "Scénario abandonné"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="tradingsettings",
            name="strategy",
            field=models.CharField(default="Non définie", max_length=500),
            preserve_default=False,
        ),
    ]
