# Generated by Django 6.0.4 on 2026-08-06 19:02

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journaling", "0014_alter_memo_planned_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="memo",
            name="planned_date",
            field=models.DateField(default=datetime.date(2026, 8, 7)),
        ),
    ]
