# Generated by Django 6.0.4 on 2026-08-12 13:05

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journaling", "0015_alter_memo_planned_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="memo",
            name="planned_date",
            field=models.DateField(default=datetime.date(2026, 8, 13)),
        ),
        migrations.AlterField(
            model_name="memo",
            name="state",
            field=models.CharField(
                choices=[
                    ("todo", "A faire"),
                    ("in_progress", "En cours"),
                    ("done", "Terminé"),
                    ("report", "Reporté"),
                    ("cancel", "Annulé"),
                ],
                default="memo",
                max_length=20,
            ),
        ),
    ]
