# Generated by Django 6.0.4 on 2026-08-13 20:37

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journaling", "0016_alter_memo_planned_date_alter_memo_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="memo",
            name="planned_date",
            field=models.DateField(default=datetime.date(2026, 8, 14)),
        ),
    ]
