# Generated by Django 6.0.4 on 2026-09-03 14:47

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journaling", "0018_add_process_today"),
    ]

    operations = [
        migrations.AlterField(
            model_name="colorparameter",
            name="periodic",
            field=models.CharField(
                choices=[
                    ("*-Every", "tous les cas"),
                    ("01-none", "01-une seule fois"),
                    ("02-everyday", "02-Tous les jours"),
                    ("03-every2days", "03-Tous les 2 jours"),
                    ("04-every3days", "04-Tous les 3 jours"),
                    ("05-every4days", "05-Tous les 4 jours"),
                    ("06-every5days", "06-Tous les 5 jours"),
                    ("07-everyweek", "07-Toutes les semaines"),
                    ("08-every10days", "08-Tous les 10 jours"),
                    ("09-every2weeks", "09-Toutes les 2 semaines"),
                    ("10-every3weeks", "10-Toutes les 3 semaines"),
                    ("11-everymonth", "11-Tous les mois"),
                    ("12-every6weeks", "12-Toutes les 6 semaines"),
                    ("13-every2months", "13-Tous les 2 mois"),
                    ("14-every3months", "14-Tous les 3 mois"),
                    ("15-every4months", "15-Tous les 4 mois"),
                    ("16-every6months", "16-Tous les 6 mois"),
                    ("17-everyyear", "17-Tous les ans"),
                    ("18-every18months", "18-Tous les 18 mois"),
                    ("19-every2years", "19-Tous les 2 ans"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="colorparameter",
            name="priority",
            field=models.CharField(
                choices=[
                    ("6-lowest", "6-Le soir"),
                    ("5-low", "5-Faible"),
                    ("4-normal", "4-Normale"),
                    ("3-medium", "3-Moyenne"),
                    ("2-high", "2-Élevée"),
                    ("1-highest", "1-Le matin"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="memo",
            name="periodic",
            field=models.CharField(
                choices=[
                    ("01-none", "01-une seule fois"),
                    ("02-everyday", "02-Tous les jours"),
                    ("03-every2days", "03-Tous les 2 jours"),
                    ("04-every3days", "04-Tous les 3 jours"),
                    ("05-every4days", "05-Tous les 4 jours"),
                    ("06-every5days", "06-Tous les 5 jours"),
                    ("07-everyweek", "07-Toutes les semaines"),
                    ("08-every10days", "08-Tous les 10 jours"),
                    ("09-every2weeks", "09-Toutes les 2 semaines"),
                    ("10-every3weeks", "10-Toutes les 3 semaines"),
                    ("11-everymonth", "11-Tous les mois"),
                    ("12-every6weeks", "12-Toutes les 6 semaines"),
                    ("13-every2months", "13-Tous les 2 mois"),
                    ("14-every3months", "14-Tous les 3 mois"),
                    ("15-every4months", "15-Tous les 4 mois"),
                    ("16-every6months", "16-Tous les 6 mois"),
                    ("17-everyyear", "17-Tous les ans"),
                    ("18-every18months", "18-Tous les 18 mois"),
                    ("19-every2years", "19-Tous les 2 ans"),
                ],
                default="partout",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="memo",
            name="planned_date",
            field=models.DateField(default=datetime.date(2026, 9, 4)),
        ),
        migrations.AlterField(
            model_name="memo",
            name="priority",
            field=models.CharField(
                choices=[
                    ("6-lowest", "6-Le soir"),
                    ("5-low", "5-Faible"),
                    ("4-normal", "4-Normale"),
                    ("3-medium", "3-Moyenne"),
                    ("2-high", "2-Élevée"),
                    ("1-highest", "1-Le matin"),
                ],
                default="4-normal",
                max_length=20,
            ),
        ),
    ]
