# Generated by Django 6.0.4 on 2026-09-10 11:51

import journaling.services
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journaling", "0019_alter_colorparameter_periodic_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="memo",
            old_name="appointment",
            new_name="event_type",
        ),
        migrations.AlterField(
            model_name="memo",
            name="planned_date",
            field=models.DateField(default=journaling.services.tomorrow),
        ),
        migrations.AlterField(
            model_name="memo",
            name="state",
            field=models.CharField(
                choices=[
                    ("todo", "À faire"),
                    ("in_progress", "En cours"),
                    ("done", "Terminé"),
                    ("report", "Reporté"),
                    ("cancel", "Annulé"),
                ],
                default="todo",
                max_length=20,
            ),
        ),
    ]
