# Generated by Django 6.0.4 on 2026-09-17 11:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journaling", "0020_rename_appointment_memo_event_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="memo",
            name="location_type",
            field=models.CharField(
                choices=[("indoor", "Intérieur"), ("outdoor", "Extérieur")],
                default="indoor",
                max_length=10,
            ),
        ),
    ]
