# Generated by Django 6.0.4 on 2026-09-03 14:47

import django.core.validators
import django_countries.fields
import escapevault.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NomadePosition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("address", models.TextField()),
                (
                    "city",
                    models.TextField(
                        max_length=40,
                        validators=[escapevault.models.validate_city_format],
                    ),
                ),
                (
                    "country",
                    django_countries.fields.CountryField(
                        countries=escapevault.models.NomadePosition.NomadeCountries,
                        default="FR",
                        max_length=2,
                    ),
                ),
                (
                    "stars",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("reviews", models.JSONField(default=list)),
                (
                    "opening_date",
                    models.CharField(
                        blank=True,
                        max_length=5,
                        null=True,
                        validators=[escapevault.models.validate_day_month_format],
                    ),
                ),
                (
                    "closing_date",
                    models.CharField(
                        blank=True,
                        max_length=5,
                        null=True,
                        validators=[escapevault.models.validate_day_month_format],
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("home", "Maison"),
                            ("nomade", "Nomade"),
                            ("love", "Coup de coeur"),
                            ("plain", "Ordinaire"),
                            ("ban", "À bannir"),
                        ],
                        default="plain",
                        max_length=100,
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(-90.0),
                            django.core.validators.MaxValueValidator(90.0),
                        ],
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(-90.0),
                            django.core.validators.MaxValueValidator(90.0),
                        ],
                    ),
                ),
                ("link_to_site", models.URLField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Nomade Position",
                "verbose_name_plural": "Nomade Positions",
            },
        ),
    ]
