# Generated by Django 6.0.4 on 2026-09-25 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SamiCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("max_score", models.PositiveIntegerField(default=25)),
            ],
        ),
        migrations.CreateModel(
            name="SamiDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True, verbose_name="Date")),
                (
                    "started_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Début"),
                ),
                (
                    "ended_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Fin"),
                ),
            ],
            options={
                "verbose_name": "Journée Sami",
                "verbose_name_plural": "Journées Sami",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="SamiIndicator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Titre")),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Règle permettant de déterminer le niveau obtenu.",
                        verbose_name="Description",
                    ),
                ),
                (
                    "max_level",
                    models.PositiveIntegerField(
                        default=5, verbose_name="Niveau maximum"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="indicators",
                        to="samicheck.samicategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Indicateur",
                "verbose_name_plural": "Indicateurs",
                "ordering": ["category", "title"],
            },
        ),
    ]
